// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ccetkeewqfjkcvnltcfb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNjZXRrZWV3cWZqa2N2bmx0Y2ZiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ3NjM5NTUsImV4cCI6MjA2MDMzOTk1NX0.pWrdRKzIc0NsiNhVEHi1Dy6L7Ya5nu6OVq4q_DQPZgM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);